Add Events Page
torchbox/wagtail-torchbox pull request #207
Opened 2020-09-24 07:45 UTC by NathHorrigan

This PR adds the Events Page that intergrates with Zoom to allow registration for Meetings and Webinars

2020-09-24 08:45 UTC, kaedroho requested changes

2020-09-24 08:45 UTC, kaedroho commented on tbx/events/events.py
> +  def __init__(self, id=None, name=None, start_time=None, join_url=None, start_url=None, event_type=None):
Please indent Python code with 4 spaces!

2020-09-24 08:45 UTC, kaedroho commented on tbx/events/events.py
> +
Also missing a space here. Please can you flake8 / black this file?

2020-09-24 08:45 UTC, kaedroho commented on tbx/events/events.py
> +class Event:
What's the purpose of this base class?

2020-09-24 08:45 UTC, kaedroho commented on tbx/events/events.py
> +    meeting = requests.get(f"https://api.zoom.us/v2/webinars/{meeting_id}", headers={
This is missing a timeout

2020-09-24 08:45 UTC, kaedroho commented on tbx/events/events.py
> +    if registration.status_code == 415:
We should log an error to Sentry here. Otherwise, we won't know if the format changes

2020-09-24 08:45 UTC, kaedroho commented on tbx/events/events.py
> +    registration = requests.post(f"{api_url}/registrants",
Also missing a timeout.

2020-09-24 08:45 UTC, kaedroho commented on tbx/events/models.py
> +from django import forms
Please flake8/black this file too. The spacing is inconsistent between classes. There's a mix of 2-space and 4-space indenting and there's a extra newline at the end (you can set your editor up to fix that last one).

2020-09-24 08:45 UTC, kaedroho commented on tbx/events/events.py
> +  def __init__(self, id=None, name=None, start_time=None, join_url=None, start_url=None, event_type=None):
This is repeated from the base class

2020-09-24 08:45 UTC, kaedroho commented on tbx/events/events.py
> +    if (self.event_type == 'meeting'):
Braces not necessary here

2020-09-24 08:45 UTC, kaedroho commented on tbx/events/events.py
> +    meeting = requests.get(f"https://api.zoom.us/v2/meetings/{meeting_id}", headers={
These URLs are repeated here from `get_api_url`.

Maybe we could simplify these methods a bit if we turned `get_api_url` into a class attribute?

For example:

```python
    API_URLS = {
        "meeting": "https://api.zoom.us/v2/meetings/{id}",
        "webinar": "https://api.zoom.us/v2/webinars/{id}",
    }

    @staticmethod
    def query_with_id(cls, event_type, id):
        url = cls.API_URLS[event_type].format(id=id)
        event = requests.get(url, headers={
            "authorization": f"Bearer {ZOOM_TOKEN}"
        }, timeout=2)

        return ZoomMeetingEvent.from_response(event, event_type)
```

2020-09-24 08:45 UTC, kaedroho commented on tbx/events/events.py
> +  def from_response(data, event_type=None):
Should `event_type` be optional?

2020-09-24 08:45 UTC, kaedroho commented on tbx/events/models.py
> +        required=True,
The `required=True` and `blank=True` appear to contradict each other.

2020-09-24 08:45 UTC, kaedroho commented on tbx/events/models.py
> +  meeting_ID = blocks.CharBlock()
`_ID` should be made lowercase

2020-09-24 08:45 UTC, kaedroho commented on tbx/events/models.py
> +class EventsPage(HeadlessPreviewMixin, Page):
Event should be singular

2020-09-24 08:45 UTC, kaedroho commented on tbx/events/views.py
> +      "error": "Invalid meeting type"
... or the registrant details are invalid

2020-09-24 08:45 UTC, kaedroho commented on tbx/graphql/schema.py
> +            for host in self.hosts.all()
Please add: `.select_related('person')`

2020-09-24 08:45 UTC, kaedroho commented on tbx/settings/base.py
> +# CORS_URLS_REGEX = r'^(\/graphql\/.*)|(\/review\/api\/.*)|(\/api\/events\/.*)$'
Why was this commented out?

2020-09-25 14:21 UTC, NathHorrigan commented on tbx/events/events.py
> +class Event:
In the future when we want to add on-site locations.

2020-09-25 14:22 UTC, NathHorrigan commented on tbx/events/events.py
> +class Event:
I was very time-constrained so didn't expand beyond what we need right now :)

2021-04-14 08:39 UTC, zerolab commented
no longer needed

2021-05-05 10:49 UTC, chris-lawton commented
Closing as per https://projects.torchbox.com/projects/tbxcom/tickets/252#update-66233611 - we're taking a slightly different approach to implementing this now - https://projects.torchbox.com/projects/tbxcom/tickets/312

2021-05-05 10:49 UTC, closed without merging