Feature: 330 careers instagram posts
torchbox/wagtail-torchbox pull request #326
Opened 2021-04-16 02:52 UTC by tbrlpld

Adds a grid gallery of instagram posts to the careers page type. 

The posts consist of an image and a link to the original post on Instagram. This is fully manual though! So images need to be uploaded to Wagtail and the link to the instagram post needs to be added completely manually. This path was chosen because of the complexities in dealing with the Instagram API (e.g. the API would require an access key that needs to be renewed at least every three months). 

Scraping was ruled out because it breaks the Instagram T&C.

2021-04-16 08:21 UTC, zerolab commented
Hey @tbrlpld, 
https://developers.facebook.com/docs/instagram/oembed, https://docs.wagtail.io/en/stable/advanced_topics/embeds.html#facebook-and-instagram (and the [actual finder](nor https://github.com/wagtail/wagtail/blob/stable/2.12.x/wagtail/embeds/finders/instagram.py)) do not mention renewing the access key

Wagtail 2.11+ support the new oEmbed endpoints for Instagram/FB so it would make a lot more sense to make use of them.

2021-04-16 08:39 UTC, chris-lawton commented on tbx/project_styleguide/templates/patterns/atoms/instagram-post/instagram-post.html
> +    <a href="{{ post.post_url }}">
as this anchor tag contains only an image and an SVG it'll need an `aria-label` adding to make it accessible, see https://dequeuniversity.com/rules/axe/4.1/link-name

2021-04-16 08:39 UTC, chris-lawton commented on tbx/project_styleguide/templates/patterns/atoms/instagram-post/instagram-post.html
> +        <img class="instagram-post__image" src="{{ image.url }}" loading="lazy" />
this could have an `alt` tag added to it

2021-04-16 08:42 UTC, chris-lawton commented on tbx/project_styleguide/templates/patterns/atoms/instagram-post/instagram-post.html
> +            <use href="#instagram" />
there was a discussion around using `href` over `xlink:href` in slack not too long ago and i think the outcome was that even though it's deprecated, it's still safer to use the latter as there were still some browsers that hadn't included support for it yet, worth double checking though. https://torchbox.slack.com/archives/C032PPZDF/p1596099102050900

2021-04-16 08:54 UTC, chris-lawton commented on tbx/static_src/sass/components/_instagram-gallery.scss
> +.instagram-post__image {
can you these elements inside the initial block declaration e.g. 
```
.instagram-post {
    &__image {
    }
    &__icon {
    }
}
```
less to change if the class is updated in the future and less to type for anyone adding to it  : )

2021-04-16 11:33 UTC, tbrlpld commented
> Hey @tbrlpld,
> 
> Kudos for the alternative approach.
> 
> https://developers.facebook.com/docs/instagram/oembed, https://docs.wagtail.io/en/stable/advanced_topics/embeds.html#facebook-and-instagram (and the [actual finder](nor https://github.com/wagtail/wagtail/blob/stable/2.12.x/wagtail/embeds/finders/instagram.py)) do not mention renewing the access key
> 
> Wagtail 2.11+ support the new oEmbed endpoints for Instagram/FB so it would make a lot more sense to make use of them. Am I missing something?

No, that sounds good. I guess that is the key difference there to the full API access that once the app is setup and live that the key remains. That is what I had expected from the beginning. 

Sorry, I must have missed that when I was looking at the docs.

2021-04-16 11:47 UTC, tbrlpld commented
@zerolab Do you know if there already is a Facebook app for the Torchbox website?

2021-04-16 11:57 UTC, zerolab commented
> @zerolab Do you know if there already is a Facebook app for the Torchbox website?

That, I'm afraid I do not know. You would need to talk to the seo/analytics teams.

2021-04-19 09:42 UTC, tbrlpld commented on tbx/project_styleguide/templates/patterns/atoms/instagram-post/instagram-post.html
> +    <a href="{{ post.post_url }}">
I will see if I can extract something useful from the oEmbed version. Otherwise this is going to be something generic like "Instagram post".

2021-04-26 06:45 UTC, tbrlpld commented
@zerolab I have now implemented the posts with the Wagtail embed block. Thanks for the pointer 👍 Would you mind taking a look at my code? 

@chris-lawton While changing to the Embed version I had to make a few changes to the Frontend code to. I have also tried to incorporate your previous comments. Would you mind taking another look at this?

2021-04-26 10:02 UTC, zerolab requested changes
@tbrlpld Looks/feels much better than previous implementation!
Added a few questions/suggestions, most are not blocking. The main thing I would change is create a custom `InstagramEmbedBlock` derived from `embed_blocks.EmbedBlock` with a url validator and some useful help text

2021-05-05 02:29 UTC, tbrlpld commented on docker-compose.yml
> -      - 6900:6900 # pudb
Not a specific decision of mine. I just pulled in the `fabfile.py` and `docker-compose.yml` from `master`. 

https://github.com/torchbox/wagtail-torchbox/commit/189ecbb6a0dc3643847fa3e7b268d4e99c1ab5eb

https://github.com/torchbox/wagtail-torchbox/blame/master/docker-compose.yml

2021-05-05 02:32 UTC, tbrlpld commented on docker-compose.yml
> +    command: tail -f /dev/null
As above, changes are coming from master, but I think without the "do nothing forever", the container would not keep running. The question as to why that is necessary on the utils container should maybe be raised on master. I believe you are right, that is probably not necessary.

2021-05-05 02:36 UTC, tbrlpld commented on tbx/people/templatetags/people_tags.py
> +def instagrampost(embed):
Fair. I think I was influenced by the navigation tags (e.g. `footernav`).

2021-05-05 04:18 UTC, tbrlpld commented
Thank @zerolab for review! I will be implementing the custom block.

2021-05-06 02:11 UTC, tbrlpld commented on tbx/people/templatetags/people_tags.py
> +def instagrampost(embed):
The custom template tag is now removed in favour of the custom embed block.

2021-05-06 02:11 UTC, tbrlpld commented on tbx/project_styleguide/templates/patterns/molecules/instagram-gallery/instagram-gallery.html
> +        {% instagrampost post %}
The custom template tag is now removed in favour of the custom embed block.

2021-05-06 04:02 UTC, tbrlpld commented on tbx/people/blocks.py
> +        local_blocks=[("post", embed_blocks.EmbedBlock())],
I have implemented the custom block now.

2021-05-11 09:49 UTC, tbrlpld commented
@zerolab I have implemented the custom embed block. This also removed the need for the template tag, as the block is not defining the rendering. 

Would be great to get you input on this version if you have a moment.

2021-05-12 02:05 UTC, tbrlpld commented
Thanks for reviewing @chris-lawton 

> I was also getting the following when testing locally, am i putting in an incorrect url?
> 
> ![image](https://user-images.githubusercontent.com/31627284/117802126-f9044f80-b24c-11eb-99ad-e956a5a36846.png)

I suspect the error coming from the fact that you need to configure the embed finder in the settings with an app id and secret. I'll slack you my `local.py` settings.

2021-05-13 09:22 UTC, zerolab approved these changes
@tbrlpld 👍🏼 

Other than the `.env` question and the `try/except` suggest, the rest are non-blocking suggestions

2021-05-13 09:22 UTC, zerolab commented on tbx/people/blocks.py
> +        template="patterns/molecules/instagram-gallery/instagram-gallery.html",
```suggestion
        template="patterns/molecules/instagram-gallery/instagram-gallery.html",
        icon="fa-instagram"
```

2021-05-18 22:10 UTC, tbrlpld commented
@chris-lawton One issue with the focus solution is that I can not rely on the instagram images to be square. When creating the embed, I have no control over what is coming in, but we want them to display as square. That is why I had to mess around with the absolute positioning, etc.

2021-05-18 22:23 UTC, tbrlpld commented
@chris-lawton can we use `:focus-within` or do we need to support IE11? 

https://caniuse.com/?search=focus-within

2021-05-18 22:25 UTC, tbrlpld commented on .env
> +FRONTEND=local
Yup, that should not be committed.

Sorry about that.

2021-05-21 20:09 UTC, tbrlpld commented
@chris-lawton I was able to solve this more simply by just removing the wrapping `div` and using the `a` element directly as the `instagram-post`.

![Screen Recording 2021-05-21 at 13 03 58](https://user-images.githubusercontent.com/24797493/119192928-b8b78500-ba35-11eb-86ed-928462db9cdc.gif)

2021-05-21 21:11 UTC, tbrlpld commented on tbx/people/blocks.py
> +        return embeds.get_embed(self.url)
Thanks for the hint @zerolab! 

I have implemented this in 72f29ed6e95407ced1b6fb26d7606b4c31bde103

2021-05-24 08:47 UTC, chris-lawton commented
Nice work @tbrlpld! LGTM

2021-05-24 09:02 UTC, zerolab approved these changes
Nice one @tbrlpld!

2021-05-24 09:23 UTC, merged

2021-06-01 14:38 UTC, tbrlpld commented
Thanks @chris-lawton and @zerolab for reviewing