WIP: [312] Events page BE
torchbox/wagtail-torchbox pull request #334
Opened 2021-05-21 15:36 UTC by chris-lawton

Adds the backend for the events based on https://projects.torchbox.com/projects/tbxcom/tickets/312#update-67103629

![Screenshot 2021-05-21 at 16 35 33](https://user-images.githubusercontent.com/31627284/119162722-9d0ea780-ba52-11eb-8595-42c56027f40c.png)

TODO: 
- [ ] Add the filters on the index page
- [ ] Add the filters to the individual events
- [ ] Allow for multiple authors to be added to an event (unsure if this is required for MVP)

2021-06-04 15:46 UTC, richbrennan commented
I haven't allowed for multiple authors as the template is set to work with one, and comment above says unsure if this is required for MVP

2021-06-18 12:10 UTC, kaedroho requested changes
One question and a requested change, but otherwise looks good to me!

2021-06-18 12:10 UTC, kaedroho commented on tbx/events/models.py
> +class Event(ClusterableModel, Orderable):
I haven't seen a clusterable child model before, do you know if this has been done elsewhere?

2021-06-18 12:10 UTC, kaedroho commented on tbx/project_styleguide/templates/patterns/pages/events/events_listing.html
> +                {% include "patterns/molecules/blog-item/blog-item.html" with item=event classes="blog-item--standout" %}
I think we should make a copy of this template for events, so this feature is decoupled from the blog. This should reduce any risk of a change being made to that template that could break the events page.

2021-06-22 15:14 UTC, richbrennan commented on tbx/events/models.py
> +class Event(ClusterableModel, Orderable):
Nope, hadn't realised I'd done it, thanks for spotting!

2021-06-23 13:26 UTC, richbrennan commented on tbx/events/models.py
> +class Event(ClusterableModel, Orderable):
It turns out I do need this, otherwise the `ParentalManyToManyField` doesn't work.

2021-06-27 21:45 UTC, kaedroho commented on tbx/events/models.py
> +class Event(ClusterableModel, Orderable):
I have a feeling that this isn't supported in Wagtail. It probably looks fine in the editor but certian features, like copying, might not work

2021-07-19 11:53 UTC, phildexter commented on tbx/events/models.py
> +class Event(ClusterableModel, Orderable):
just spoke to Karl. This would need a fix in wagtail core to get this many to many in an inline panel working perfectly.

At the moment we've agreed we can deploy this as is, and just know that if we copy the page we'll not have the same content on the copied page (can't see this being an issue here).

2021-07-20 09:06 UTC, merged