WIP: Accessibility Audit Fixes
torchbox/wagtail-torchbox pull request #378
Opened 2021-12-15 16:31 UTC by jhancock532

This branch includes all the fixes from the accessibility audit spreadsheet, as well as some incidental fixes noticed during development.

The first 8 commits resolve the blocking severity issues found. Note that the tabbing system to show more posts focuses on a new element when activated, this may require closer review.

2021-12-16 17:34 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/molecules/title-block/title-block.html
> +        <div class="title-block__tags" aria-label="Filter blog posts by category">
This unfortunately won't work as aria-labels aren't valid on `<div>` elements, so it won't be read aloud. Might be better to add some SR-only text here which is visually hidden. We usually have a 'u-sr-only' class for this sort of thing. Handy reference: https://webaim.org/techniques/css/invisiblecontent/

2021-12-20 16:56 UTC, jhancock532 commented on tbx/project_styleguide/templates/patterns/molecules/title-block/title-block.html
> +        <div class="title-block__tags" aria-label="Filter blog posts by category">
Do you have any screen reader software you recommend testing with? I've noticed that with mac VoiceOver the sr-only text is not read aloud, whereas the above aria label on the div is.

2022-01-04 10:59 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/molecules/title-block/title-block.html
> +        <div class="title-block__tags" aria-label="Filter blog posts by category">
Oh interesting, are you testing with Voiceover in Safari? That's the most reliable combo. I'll spin it up and do some further testing.

2022-01-04 12:36 UTC, janehughes requested changes
Looking good so far James, thank you!! I've added a few comments/suggestions. Lets get the branch added to the main repo instead - I'll do a bit more thorough testing once that's up 👍 let me know if you have any issues

2022-01-04 12:36 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/atoms/animated-characters/wagtail.html
> +        <path class="wagtail_svg__eyes" d="M588.7 172.8c6.1 11.2 1.9 25.1-9.2 31.2-10.8 5.9-24.2 2.3-30.6-8.2l39.8-23z"></path>
I'll do some testing of this once you've got the new branch created, but just to double check this isn't going to impact the animation of the figures at all, just the colours?

2022-01-04 12:36 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/atoms/animated-characters/women.html
> +        <path class="help-character_svg__cls-6" d="M127.41 179.18a20.13 20.13 0 1 0 34.86 20.13z"></path>
Same question as above for this one

2022-01-04 12:36 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/atoms/instagram-post/instagram-post.html
> +<a class="instagram-post" href="{% if post.value.link %}{{ post.value.link }}{% else %}https://www.instagram.com/torchboxltd/{% endif %}" target="_blank" rel="nofollow noreferrer">
👍

2022-01-04 12:36 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/atoms/menu-button/menu-button.html
> +<button class="menu-button" aria-label="Menu toggle" data-menu-toggle data-active="menu">
🙌

2022-01-04 12:36 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/molecules/author/author.html
> +    <span class="author__sr-only">,</span>
I suggest creating a global class to use for SR-only text, so you don't need to keep creating component-specific classes every time you need hidden text :)

2022-01-04 12:36 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/molecules/blog-item/blog-item.html
> +    <h2 class="blog-item__title">{{ item.title }}</h2>
👍

2022-01-04 12:36 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/molecules/blog-item/blog-item.html
> +    <span class="blog-item__hidden-comma">,</span>
Same suggestion as above, lets create a global class for these

2022-01-04 12:36 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/molecules/event-item/event-item.html
> +    <span class="blog-item__hidden-comma">,</span>
And here :)

2022-01-04 12:36 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/molecules/help-block/help-block.html
> +                            <a href="mailto:{{ contact.email_address }}" class="help-block__contact help-block__contact--email" aria-label="Will's email address">
Small suggestion, it might be helpful to label this something like 'Email our New Business Director Will' so users know who he is

2022-01-04 12:36 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/molecules/help-block/help-block.html
> +                            <a href="tel:{{ contact.phone_number }}" class="help-block__contact help-block__contact--phone" aria-label="Will's phone number">
Same as above

2022-01-04 12:36 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/molecules/list-item/list-item.html
> +    <svg class="list-item__icon" fill="#fd5765" viewBox="0 0 298 298" aria-hidden="true">
🙌

2022-01-04 12:36 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/molecules/navigation/primary-nav.html
> +        <button class="nav-item__button" @click="isOpen = !isOpen" :aria-expanded="isOpen" aria-controls="dropdown-nav-menu">
👍

2022-01-04 12:36 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/organisms/page-contact/page-contact.html
> +                            <a href="mailto:willh@torchbox.com" aria-label="Will's email address" class="contact-block__email">willh@torchbox.com</a>
As above, may be helpful to add the context to these links so Will's title is read aloud

2022-01-04 14:27 UTC, jhancock532 commented on tbx/project_styleguide/templates/patterns/molecules/title-block/title-block.html
> +        <div class="title-block__tags" aria-label="Filter blog posts by category">
I was using voiceover on Chrome, which might have given the different result 🤔 I will add the u-sr-only class following the suggestions you've made below

2022-01-04 14:29 UTC, jhancock532 commented on tbx/project_styleguide/templates/patterns/atoms/animated-characters/wagtail.html
> +        <path class="wagtail_svg__eyes" d="M588.7 172.8c6.1 11.2 1.9 25.1-9.2 31.2-10.8 5.9-24.2 2.3-30.6-8.2l39.8-23z"></path>
Yep, this just changes the colours 👍

2022-01-04 14:47 UTC, jhancock532 commented on tbx/project_styleguide/templates/patterns/molecules/title-block/title-block.html
> +        <div class="title-block__tags" aria-label="Filter blog posts by category">
I've tested across chrome and safari - Chrome skips the sr-only text when you tab directly to the filter options, but it will read it out if you don't tab through the page. Chrome will read out the aria label as a group title if you tab to the filter options directly, which could be a benefit of keeping it in if you don't mind hearing it twice. Safari doesn't read out the aria label if you tab to the page filter - in fact, tabbing on this page (/blog/) doesn't seem to work on Safari, even though it works on Chrome fine.

2022-03-17 11:37 UTC, janehughes approved these changes
There's just one small suggestion I've made to add an empty alt tag. Otherwise I've been through your other fixes and everything's looking good to me James, thanks so much and apologies this has taken so long to get round to reviewing.

Lets get this merged! 🎉

2022-03-17 11:37 UTC, janehughes commented on tbx/project_styleguide/templates/patterns/molecules/team-member/team-member.html
> +        <img class="team-member__image" src="{{ image.url }}" aria-hidden="true" width="{{ image.width }}" height="{{ image.height }}" loading="lazy">
```suggestion
        <img class="team-member__image" src="{{ image.url }}" aria-hidden="true" width="{{ image.width }}" height="{{ image.height }}" loading="lazy" alt="">
```

2022-04-08 15:47 UTC, merged