M1 Setup Documenation
torchbox/wagtail-torchbox pull request #383
Opened 2022-03-18 15:54 UTC by jhancock532

Notes on setting up development in the repository for M1 mac users. I've decided to add this since Jane ran into the same issues I did whilst setting up, so this should hopefully clarify the process required for future developers.

This is a stopgap documentation measure - ideally changes could be made so that M1 users automatically load different heroku and redis installs.

2022-03-21 16:13 UTC, thibaudcolas requested changes
@jhancock532 all of those changes look good to me but they all seem like they’d be valuable to all contributors, not just people with M1 computers. Could you update the relevant Docker configuration files and the README with equivalent changes?

2022-03-21 16:13 UTC, thibaudcolas commented on docs/M1 Setup Instructions.md
> +```
I see we’re running Redis 6 in production anyway – would you be ok to make this change directly to the `docker-compose.yml` for everyone?

2022-03-21 16:13 UTC, thibaudcolas commented on docs/M1 Setup Instructions.md
> +Make sure you've updated Heroku to the latest version (with `heroku update`) or you will be denied access.
This doesn’t seem specific to M1 macs, could you update the main README?

2022-03-21 16:13 UTC, thibaudcolas commented on docs/M1 Setup Instructions.md
> +```
Here as well, I’d prefer we switch to this for everyone. Could you make the changes to `Dockerfile.utils` directly?

2022-03-21 16:13 UTC, thibaudcolas commented on docs/M1 Setup Instructions.md
> +## Docker Setup
Same as the above – none of this seems specific to M1 laptops, so I’d prefer you made corresponding updates for what you have below to the different parts of the README.

2022-03-21 16:13 UTC, thibaudcolas commented on docs/M1 Setup Instructions.md
> +`fnm use` (or `nvm use` if you haven't installed `fnm` yet. Note that `fnm` is far faster.)
I’d prefer we mention `nvm` first and `fnm` second, as most of our existing projects recommend nvm – it’s more likely people will have this installed. If we want to recommend fnm here, we should have a link to it so people know how to install.

2022-03-21 16:13 UTC, thibaudcolas commented on docs/M1 Setup Instructions.md
> +`fab destory`
```suggestion
`fab destroy`
```

2022-03-21 16:13 UTC, thibaudcolas commented on docs/M1 Setup Instructions.md
> +`./manage.py runserver 0.0.0.0:8000` (Brings the site online)
We should be using code blocks for things like this, as otherwise this will all get concatenated into a single line when rendered in GitHub/GitLab.

2022-03-22 17:08 UTC, jhancock532 commented
This is now ready for 'non M1' testing, apart from an issue with running the FE tooling in the Docker container. The FE tooling currently only works locally, I'm looking into the issue now.

This might be related to [!384 - Increase Minor Node Version](https://github.com/torchbox/wagtail-torchbox/pull/384).

2022-03-23 02:12 UTC, thibaudcolas approved these changes
Looks great to me!

2022-03-23 02:12 UTC, thibaudcolas commented on README.md
> +./manage.py runserver 0.0.0.0:8000
```suggestion
./manage.py runserver 0:8000
```

I believe we prefer this style simply because it’s shorter.

2022-03-23 14:12 UTC, nimasmi commented
> This is now ready for non M1 testing, it would be great to test this on an older Mac and a Linux device.

I tried this just now on Linux. Running `fab build`, I got an error from https://github.com/torchbox/wagtail-torchbox/blob/docs/M1-setup-instructions/Dockerfile#L12, but it doesn't immediately look related to this PR.

```
Step 6/22 : RUN npm run build:prod
 ---> Running in f13aaecae9b6

> Torchbox@0.0.0 build:prod /
> npm-run-all clean compile:prod


> Torchbox@0.0.0 clean /
> rm -rf $npm_package_config_dist/*


> Torchbox@0.0.0 compile:prod /
> webpack --mode production

[webpack-cli] HookWebpackError: Only file and data URLs are supported by the default ESM loader
    at makeWebpackError (/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /node_modules/webpack/lib/Compilation.js:3055:12
    at eval (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:40:1)
    at /node_modules/webpack/lib/Compilation.js:508:26
    at /node_modules/copy-webpack-plugin/dist/index.js:705:13
-- inner error --
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:781:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36)
caused by plugins in Compilation.hooks.processAssets
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:781:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! Torchbox@0.0.0 compile:prod: `webpack --mode production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the Torchbox@0.0.0 compile:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-23T14_06_13_667Z-debug.log
ERROR: "compile:prod" exited with 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Torchbox@0.0.0 build:prod: `npm-run-all clean compile:prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Torchbox@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-23T14_06_13_687Z-debug.log
```

2022-03-25 15:55 UTC, jhancock532 commented on README.md
> +./manage.py runserver 0.0.0.0:8000
Ah, I used this style once on an older project and it wouldn't run the server, so I always tend to go for 0.0.0.0 just in case

2022-03-29 12:56 UTC, thibaudcolas commented
@nimasmi this does look very unrelated. Would you be ok to open a ticket for this?

2022-03-29 13:15 UTC, nimasmi commented on README.md
> +As the above commands won't run on Linux, identify the running Docker processes with
`fab stop` and `fab destroy` will work fine. I thought you had some Docker desktop commands in the Mac OS X section previously.

2022-03-29 15:50 UTC, nimasmi commented on README.md
> +As the above commands won't run on Linux, identify the running Docker processes with
Ah, yes, you still do. Only "Restart docker desktop if old docker instances don't want to quit." is Mac OS-specific.

2022-04-04 09:33 UTC, jhancock532 commented on README.md
> +As the above commands won't run on Linux, identify the running Docker processes with
Thank you, updating this now

2022-04-04 09:45 UTC, merged