365 Footer
torchbox/wagtail-torchbox pull request #385
Opened 2022-03-24 16:28 UTC by chris-lawton

- Implement revised footer
- Remove contact block as this info has been moved to the footer 

<details>
<summary>
Desktop and Mobile screenshots in here
</summary>

![Screenshot 2022-03-24 at 16 25 07](https://user-images.githubusercontent.com/31627284/159964075-394f3fb2-894b-4656-89d1-5d8a25fb7e98.png)

![Screenshot 2022-03-24 at 16 25 38](https://user-images.githubusercontent.com/31627284/159964083-81558985-15e2-496b-b561-6e59e3c21626.png)

</details>

2022-03-30 08:42 UTC, jhancock532 requested changes
I've picked up some changes to keep the footer design consistent across both sites, looking good so far 👍

2022-03-30 08:42 UTC, jhancock532 commented on tbx/static_src/sass/components/_footer.scss
> +        margin: ($grid * 2) 0 math.div($grid, 2) 0;
```suggestion
        margin: ($grid * 2) 0 ($grid * 0.5) 0;
```
Is what I typically go for when I want to do divisions by two, not sure if `div` offers any advantages here

2022-03-30 08:42 UTC, jhancock532 commented on tbx/static_src/sass/components/_footer.scss
> +    padding: ($grid * 2) 0;
Feedback from Ben E. in design review was to add more padding to this footer section on mobile

<details><summary>Screenshots</summary>
Current footer
<img width="630" alt="image" src="https://user-images.githubusercontent.com/18164832/160785979-b0848785-3df8-4168-9b58-ccd2bb6f9f5d.png">
Expected padding, `($grid * 1.5)` in total I think
![image](https://user-images.githubusercontent.com/18164832/160786312-7d3e53f4-e2b5-47d8-b23b-27317558ffeb.png)
</details>

2022-03-30 08:42 UTC, jhancock532 commented on tbx/static_src/sass/components/_footer.scss
> +        justify-content: center;
On my footer I've aligned these left, not sure which design is preferrable

<details><summary>Screenshots</summary>
<img width="663" alt="image" src="https://user-images.githubusercontent.com/18164832/160787578-499c11f9-9627-41b9-9db4-00cc93dd469f.png">
![image](https://user-images.githubusercontent.com/18164832/160787712-6739ebe0-cd43-48dd-92bf-639e8b2d6940.png)
</details>

2022-03-30 08:42 UTC, jhancock532 commented on tbx/static_src/sass/components/_footer.scss
> +            color: var(--color--coral);
```suggestion
            color: var(--color--coral--dark);
```

2022-03-30 08:42 UTC, jhancock532 commented on tbx/project_styleguide/templates/patterns/organisms/footer/footer.html
> +                <p class="footer__contact-desc">If you got a brief, we&apos;d love to see it. If you haven&apos;t, talk to us before you write it, we can help.</p>
```suggestion
                <p class="footer__contact-desc">If you&apos;ve got a brief, we&apos;d love to see it. If you haven&apos;t, talk to us before you write it, we can help.</p>
```

2022-03-30 08:42 UTC, jhancock532 commented on tbx/static_src/sass/components/_footer.scss
> +        @include font-size(ml);
Please could you add `font-weight: $weight--extrabold;` here, you'll have to set this value in the `variables.scss` to `900`. You'll also need to add the `ml` font scaling to the `variables.scss` as well, as this is a custom font scale from the new designs.

2022-03-30 08:42 UTC, jhancock532 commented on tbx/static_src/sass/components/_footer.scss
> +            max-width: $site-width;
I think we wanted to keep the old footer design on the homepage, but I'm not sure about this.

2022-03-30 08:42 UTC, jhancock532 commented on tbx/static_src/sass/components/_contact-slim.scss
I added a coral-dark border bottom on hover / focus here to show interactivity

2022-04-01 09:43 UTC, chris-lawton commented on tbx/project_styleguide/templates/patterns/atoms/sprites/sprites.html
> +    <circle cx="19.332" cy="16.413" r="4.022" stroke="#FD5765" stroke-linecap="round" stroke-width="2" transform="rotate(12.265 19.332 16.413)"></circle>
Great suggestion - thanks James! : )

2022-04-01 09:45 UTC, chris-lawton commented on tbx/project_styleguide/templates/patterns/molecules/locations/locations.html
> +    {% if global_settings.addresses %}
The line breaks are rendered from the rick text block in wagtail so we can just remove them in there to match the careers site 👍

2022-04-01 09:49 UTC, chris-lawton commented on tbx/static_src/sass/components/_footer.scss
> +        margin: ($grid * 2) 0 math.div($grid, 2) 0;
I think either way is fine. Previously this would have looked like `($grid / 2)` however using a slash for a division is being removed and the suggestion is to either use `calc` or `@use 'sass:math'` so i've gone for the latter here. Relevant article relating to the breaking change: https://sass-lang.com/documentation/breaking-changes/slash-div#automatic-migration

2022-04-01 09:54 UTC, chris-lawton commented on tbx/static_src/sass/components/_footer.scss
> +    padding: ($grid * 2) 0;
More top/bottom padding? Would we want `($grid * 2.5)` for this? On the homepage the left/right padding lines up with the content above which i'd think we'd want to keep.

2022-04-01 10:04 UTC, chris-lawton commented on tbx/static_src/sass/components/_footer.scss
> +        justify-content: center;
I'll update this to match the careers site 👍

2022-04-01 10:06 UTC, chris-lawton commented on tbx/project_styleguide/templates/patterns/organisms/footer/footer.html
> +                <p class="footer__contact-desc">If you got a brief, we&apos;d love to see it. If you haven&apos;t, talk to us before you write it, we can help.</p>
nice catch

2022-04-01 10:10 UTC, chris-lawton commented on tbx/static_src/sass/components/_footer.scss
> +        @include font-size(ml);
Will 800 suffice do you think? It doesn't look like the 900 weight of the font is being loaded in https://github.com/torchbox/careers/blob/main/styles/_fonts.scss or https://github.com/torchbox/wagtail-torchbox/blob/master/tbx/static_src/sass/base/_fonts.scss. Feels like it might be overkill loading in two font-weights so close to another but I could be wrong.

2022-04-01 10:11 UTC, chris-lawton commented on tbx/static_src/sass/components/_footer.scss
> +        @include font-size(ml);
Thanks for the spot on the `ml`. I'll get that added 👍

2022-04-01 10:13 UTC, chris-lawton commented on tbx/static_src/sass/components/_footer.scss
> +        @include font-size(ml);
On review the `ml` font from the careers site is smaller than the `m` size so i'll need to rename appropriately

2022-04-01 10:19 UTC, chris-lawton commented on tbx/static_src/sass/components/_footer.scss
> +            max-width: $site-width;
Looking at the initial designs (https://projects.torchbox.com/projects/tbxcom/tickets/365#update-68609631) the footer has been added to the homepage and other pages so think we're safe to assume this is a global change.

2022-04-01 10:31 UTC, chris-lawton commented on tbx/static_src/sass/components/_contact-slim.scss
I'll match that

2022-04-04 09:51 UTC, jhancock532 commented
This looks great! All the fixes work as expected. Apologies for not raising this earlier, please could you make one final change to add a container with `max-width: 1440px;` and `margin: 0 auto;` that will keep the footer contents condensed on larger screens, as shown below:

Current careers site:
![image](https://user-images.githubusercontent.com/18164832/161519222-44b5a9c1-8956-4608-bc82-ced67a289418.png)

Current staging site:
![image](https://user-images.githubusercontent.com/18164832/161518971-12d9ba91-0375-4ac2-b2d6-3fab0c9879ee.png)

2022-04-04 10:36 UTC, chris-lawton commented
Good spot on the footer max width @jhancock532. I've updated it to match the careers site and pushed to staging. I've used slightly different padding on the homepage compared to the rest of the site so the footer contents aligns with the content that's above it.

2022-04-04 13:05 UTC, jhancock532 approved these changes

2022-04-06 09:13 UTC, merged