Draft: Integration branch for new proposition landing page
torchbox/wagtail-torchbox pull request #405
Opened 2022-08-25 13:32 UTC by helenb

Includes the following PRS:

!403
!404

2022-11-03 10:18 UTC, ababic commented on tbx/services/models.py
>          service_page = ServicePage.objects.ancestor_of(self).live().last()
We can add select_related("service") to both of these lines for a quick performance win

2022-11-03 11:40 UTC, ababic approved these changes

2023-01-11 11:44 UTC, William-Blackie requested changes
Hey all, there's a couple of things we should take care of before we can ship it. It should be pretty straight forward though!

2023-01-11 11:44 UTC, William-Blackie commented on tbx/core/blocks.py
> +class LinkBlock(StreamBlock):
Issue: Defining this as a streamblock and relying max_num to prevent more than one and then on indexing the first value feels a work around that does not need to exist.

Something like this removes this issue:

```
class LinkStructValue(StructValue):
    def url(self):
        external_url = self.get('external_link')
        internal_link = self.get('internal_link')
        return external_url or internal_link.url

class LinkBlock(blocks.StructBlock):
    internal_link = blocks.PageChooserBlock(required=False)
    external_link = blocks.URLBlock(required=False)

    class Meta:
        icon = 'link'
        template = 'utils/blocks/internal_external_link.html'

    def clean(self, value):
        errors = {}
        if value.get('internal_link') and value.get('external_link'):
            msg =  'Only one of these fields should be filled out.'
            errors['internal_link'] = ErrorList([
                msg
            ])
            errors['external_link'] = ErrorList([
                msg
            ])

        if not value.get('internal_link') and not value.get('external_link'):
            msg = 'You must fill out one of these fields.'
            errors['internal_link'] = ErrorList([
                msg
            ])
            errors['external_link'] = ErrorList([
                msg
            ])

        if errors:
            raise ValidationError('Validation error in InternalExternalLinkBlock', params=errors)

        return super(InternalExternalLinkBlock, self).clean(value)

    class Meta:
        value_class = LinkStructValue
```

2023-01-11 11:44 UTC, William-Blackie commented on tbx/core/blocks.py
> +class LinkBlock(StreamBlock):
Please note that the FE templates using `link.value.o` needs changing to `link.url`

2023-01-11 11:44 UTC, William-Blackie commented on tbx/project_styleguide/templates/patterns/pages/careers/careers_page.html
> +        {% include "patterns/molecules/hero/hero--full-screen.html" with background_url=hero_image.url classes="hero__full-screen--short hero__full-screen--image-overlay" %}
Question: Why are we using BEM notation for filenames?

2023-01-11 11:44 UTC, William-Blackie commented on tbx/propositions/models.py
> +INTRO_RICHTEXT_FEATURES = ["bold", "italic", "link", "document-link", "strikethrough"]
Suggestion: Move this to it's own constant.py file, we don't have to but seperation is useful.

2023-01-11 11:44 UTC, William-Blackie commented on tbx/services/models.py
> +        try:
Issue: Why is this code repeated?

2023-01-11 11:44 UTC, William-Blackie commented on tbx/static_src/sass/components/_hero.scss
> +            top: 0;
Suggestion: Use `inset: 0;` here instead of using four properties to set the position

2023-01-17 15:05 UTC, William-Blackie commented on tbx/services/models.py
> +        try:
Weird, coming back to fix this, the diff has changed. Nothing to change.

2023-01-17 15:11 UTC, William-Blackie commented on tbx/core/blocks.py
> +class LinkBlock(StreamBlock):
So, having picked this up to implement it, I know understand more about why these blocks were approached this way. 

It's not ideal and clearly is a work around due to how values are passed between blocks / child blocks (https://github.com/wagtail/wagtail/issues/5300#issuecomment-555708044). However, there's no way to keep the individual external and internal links in seperate classes without either combining them and writting custom validation in that inherited class or without writting a custom component to do so. 

Hopefully this can be fixed in a later iteration of Wagtail with the Streamfield API as is discussed on that ticket.

2023-01-17 15:12 UTC, William-Blackie approved these changes

2023-01-17 15:12 UTC, merged