Add github actions for flightpath
torchbox/wagtail-torchbox pull request #428
Opened 2022-12-07 11:06 UTC by victoriachan

Add flightpath as github actions: https://projects.torchbox.com/projects/support-team/tickets/641 (requires support/birdbath) to be deployed first.

2022-12-13 11:35 UTC, b-ggs approved these changes
LGTM!

2022-12-14 16:16 UTC, zerolab requested changes

2022-12-14 16:16 UTC, zerolab commented on .github/workflows/flightpath.yml
> +          -H "Authorization: Token ${{ secrets.FLIGHTPATH_AUTH_KEY }}" -d "source_key=${{ secrets.DEPLOYMENT_KEY }}&destination_key=${{ secrets.DEPLOYMENT_KEY }}&copy_media=1&from_backup=1"
I am still not OK with this as it these will appear in the action logs.

As mentioned in Slack, I'd very much prefer to move it to a python script

2022-12-15 09:15 UTC, victoriachan commented on .github/workflows/flightpath.yml
> +          -H "Authorization: Token ${{ secrets.FLIGHTPATH_AUTH_KEY }}" -d "source_key=${{ secrets.DEPLOYMENT_KEY }}&destination_key=${{ secrets.DEPLOYMENT_KEY }}&copy_media=1&from_backup=1"
I've now moved it to python script.

2022-12-15 12:25 UTC, zerolab requested changes

2022-12-15 12:25 UTC, zerolab commented on .github/workflows/flightpath.yml
> +      - name: Set up Python 3.9
question: any reason not to use 3.11 and benefit from its performance improvements?

2022-12-15 12:25 UTC, zerolab commented on .github/workflows/flightpath.yml
> +          pip install argparse
```suggestion
          python -m pip install requests
```

2022-12-15 12:25 UTC, zerolab commented on .github/workflows/flightpath.yml
> +          pip install argparse
argparse is part of the Python standard library as of Python 3.2

https://docs.python.org/3/library/argparse.html

2022-12-15 12:25 UTC, zerolab commented on tbx/core/utils/run_flightpath.py
> +    run_id = (os.environ.get("GITHUB_RUN_ID"),)
question: why are these defined as tuples?

2022-12-15 12:25 UTC, zerolab commented on tbx/core/utils/run_flightpath.py
> +            "You need the following environment variables to run flightpath: FLIGHTPATH_URL, HEROKU_APP_NAME_PRODUCTION, FLIGHTPATH_AUTH_KEY, DEPLOYMENT_KEY. This should be set on github secrets if r
nitpick: `github` -> `GitHub`, `github actions` -> `GitHub Actions` everywhere

2022-12-15 12:25 UTC, zerolab commented on tbx/core/utils/run_flightpath.py
> +    print(f"from Github repository: {repository}, run_id: {run_id}.")
is the intetion for this only to run as part of GitHub Actions? if so, best to move it to `.github/`. Otherwise, perhaps tweak this note

2022-12-16 11:32 UTC, victoriachan commented on tbx/core/utils/run_flightpath.py
> +    print(f"from Github repository: {repository}, run_id: {run_id}.")
I was thinking of making the script reusable so it can be added to Kit. It can potentially be called from gitlab CI or  be used by fabric or django-admin commands.

2022-12-16 11:34 UTC, victoriachan commented on .github/workflows/flightpath.yml
> +      - name: Set up Python 3.9
No reason not to! I've updated it now.

2022-12-16 11:47 UTC, zerolab commented on .github/workflows/flightpath.yml
> +          python-version: 3.11
missed that earlier:

```suggestion
          python-version: '3.11'
```

2022-12-16 12:00 UTC, zerolab commented on tbx/core/utils/scripts/run_flightpath.py
> +        # Don't accidentally run on prod!
just nitpicking here: if one sets the wrong apps in the env vars it will happen anyway.

Been thinking.. since we're setting everything else as an env var, do we need to pass destination as an argument? why not read it from the env like the source/keys?

2022-12-16 12:07 UTC, victoriachan commented on tbx/core/utils/scripts/run_flightpath.py
> +        # Don't accidentally run on prod!
I wanted to make it harder to accidentally run it. Specifiying the destination makes it more deliberate. Sort of like Heroku making you retype the app now before it lets you delete it. Though it still won't be much help if someone just uses command line history to run it. What do you think? It is rather awkward.

2023-01-03 13:20 UTC, nickmoreton commented on .github/workflows/flightpath.yml
> +on: [workflow_dispatch]
**Question**
I wonder if this could be adjusted so the manual command can be run from a staging pipeline, like we do in gitlab?

Then this could be tested by only pushing to staging.

2023-01-03 13:32 UTC, victoriachan commented on .github/workflows/flightpath.yml
> +on: [workflow_dispatch]
I don't think so.

https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow  

“To run a workflow manually, the workflow must be configured to run on the workflow_dispatch event. To trigger the workflow_dispatch event, your workflow must be in the default branch.”

2023-01-03 13:36 UTC, nickmoreton commented on .github/workflows/flightpath.yml
> +on: [workflow_dispatch]
Sorry I posted this on slack :) 

So is this where you mentioned you could changed the branch: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch (scroll down a little to the Run workflow button)

And a little lower down it mentions limiting the branches: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#limiting-your-workflow-to-run-based-on-branches

I haven't explored this much so I may be missing something.

2023-01-03 14:57 UTC, nickmoreton approved these changes
The code looks to me to be ready to run the command and looks good. If it can only be run from the master branch that seems OK to me.

I'd need to put together a quick test repo to try out getting the button available on other branches because I don't completely understand the docs. 🙁

2023-01-05 09:12 UTC, victoriachan commented on .github/workflows/flightpath.yml
> +on: [workflow_dispatch]
This is what I found when testing on my fork: Once this is on master, admins will then see the 'copy prod to staging' option in the 'Actions' tab on Github website. When clicking on this, you can then choose to run the workflow using the script from a selected branch. Here you could choose staging if you like. But the option only appears if some form on this action is on the master/default branch first.

2023-01-16 15:06 UTC, alxbridge commented
Hi @victoriachan - you've addressed all the review feedback left by others, and this looks fine to me too.

If you wanted to test this before it's merged, I like the approach [suggested here](https://stackoverflow.com/a/65389878): creating a dummy workflow with the same name in `master`, causing the workflow to be registered in Github and allowing you to select your branch's version to run instead.

2023-02-10 11:04 UTC, katdom13 commented
Hi @victoriachan ,
This also looks good to me. Thank you!

2023-03-01 09:08 UTC, victoriachan commented on tbx/core/utils/scripts/run_flightpath.py
> +        # Don't accidentally run on prod!
I have changed this now.

2023-03-01 09:09 UTC, merged