#223 Service Process add external link
torchbox/wagtail-torchbox pull request #453
Opened 2023-03-07 16:53 UTC by estyxx

2023-03-08 11:29 UTC, victoriachan requested changes
Some tiny tweaks required for the template conditionals and an optional suggestion about using request with get_url.

2023-03-08 11:29 UTC, victoriachan commented on tbx/services/models.py
> +            return self.page_link.url
Suggestion: `get_url` (which is what .url is behind the scenes) accepts a `request` argument, which can massively help performance. It might be better to do this switching in the template, so `{% page_url %}` can be used. 

Though in this case there is only one link (i.e. not looping through a bunch of pages), and the way you've done it does look cleaner. So it's up to you to weight performance vs code clarity.

2023-03-08 13:58 UTC, estyxx commented on tbx/project_styleguide/templates/patterns/molecules/process-item/process-item.html
>      {% if item.page_link %}
nice spot!

2023-03-09 10:31 UTC, victoriachan commented on tbx/services/models.py
> +            return self.page_link.url
Sorry if I wasn't clear before. What I meant is that providing the optional `request` argument [improves performance](https://github.com/wagtail/wagtail/blob/main/wagtail/models/__init__.py#L2128-L2131). It would be great if you could use `get_url(request)` but unfortunately `request` isn't available here to use in custom properties.

The alternative is to move this entire conditional logic to the template, so instead of using your convenient custom `item.link`, you do this  e.g.

```
{% if item.external_link %}
      <a href="{{ item.external_link }}">
{% elif item.page_link %}
      <a href="{% pageurl item.page_link %}">
{% endif %}
```

It does seem more clunky having this logic on the template. But it improves performance.

2023-03-09 10:34 UTC, victoriachan approved these changes
Hi Ester, looks good. I have replied regarding pageurl. It is just a suggestion, so happy to approve this as it is.

2023-03-09 14:53 UTC, merged