422 - FE styling issues | Proposition pages
torchbox/wagtail-torchbox pull request #463
Opened 2023-03-13 15:43 UTC by cassidydvl

[Ticket 422
](https://projects.torchbox.com/projects/tbxcom/tickets/422)

- fix header colors not reaching top of page
- quote spacing
- add streamfield section spacing
- theme--dark class overrides for proposition section (theme--dark seems to be used globally so was cautious about making changes to this class)

2023-03-14 08:16 UTC, helenb commented
Hi @cassidydvl I've changed this MR to point at `master` rather than `staging`. Once I've approved it, you can merge your branch into `staging` on your machine and push the `staging` branch to deploy it - leaving this MR in place for when it's been approved to go to production - does that make sense?

2023-03-14 09:04 UTC, helenb requested changes
Hi @cassidydvl, some good fixes here, but I don't think overriding the theme css vars is quite working, so needs looking again. I think an approach of finding where the link text is white and overriding this for the proposition pages is the best one - I think this is usually determined by the `.streamfield` class. Alternatively we could see if there is a way to remove the `streamfield` class for the proposition pages.

2023-03-14 15:58 UTC, helenb commented on tbx/static_src/sass/components/_theme.scss
> +            --color--link: var(--color--dark-indigo);
We discussed this in our call and Cassidy pointed out that the designs use the coral colour everywhere, so this does look correct. There's an issue with the hover state on the bottom borders not being quite right though - it might need to be a bit thicker.

Also, it might be best to override these css vars where we set the other styles for `.proposition-section` rather than nesting them here. Likewise the border hover style could be amended where the other `.streamfield` styles are defined.

Checking linting with `npm run lint`

2023-03-14 16:01 UTC, helenb commented on tbx/static_src/sass/components/_theme.scss
> +        --color--section-title: var(--color--coral);
Design shows this as coral everywhere so we'll leave it and make sure Anna is aware.

2023-03-14 23:42 UTC, cassidydvl commented on tbx/static_src/sass/components/_hero.scss
> +            top: 280px;
@helenb went this route just incase we want to bump up the image size like the design but some overflow issues were present with the image

2023-03-14 23:44 UTC, cassidydvl commented on tbx/static_src/sass/components/_key-points.scss
> +    & &__link {
@helenb ran into some specificity issues, the .key-points parent class was being removed and streamfield styles were overriding without it, not sure this is the cleanest way to accomplish it

2023-03-14 23:45 UTC, cassidydvl commented on tbx/static_src/sass/components/_key-points.scss
> +        }
@helenb we could either remove the border or thicken it, i think the nice transition gets lost with the border

2023-03-15 09:06 UTC, helenb requested changes
Thanks @cassidydvl - a couple more tweaks needed here. Could you also check the linting again - I think it is complaining about prettier this time. You can fix that by running `npm run format` in the terminal, but it would be great to get your editor set up to run prettier on save - Steve should be able to help you with that as I'm not around later.

2023-03-15 09:06 UTC, helenb commented on tbx/static_src/sass/components/_key-points.scss
> +    & &__link {
Suggestion: change to

```
&__link {
        .streamfield & {
            @include link-slide-right(4px, -5px);
            &:hover {
                border-bottom: 0;
            }
        }
    }
```

That way it is clear what style you are overriding.

2023-03-15 16:01 UTC, cassidydvl commented on tbx/static_src/sass/components/_hero.scss
> +            // right: -400px;
Apologies! I meant to have a chat about this and demonstrate. The commented code:
```
// right: -400px;
// width: 75vw;
```
is more consistent with the size of the image in the design but there is overlapping issues and overflow: visible set on [line 90](https://github.com/torchbox/wagtail-torchbox/pull/463/commits/a4d14d00c7a139d39d3a71b3465710637bc607ab#diff-46174d8126148a2383e0533f71f0795d90b7396391cae50630086f4952d5d0ceR90) so I'm assuming this was intentional? What do you think? Leave the size as is and position it to not overlap as suggested above?

2023-03-15 16:04 UTC, cassidydvl commented on tbx/static_src/sass/components/_key-points.scss
> +    & &__link {
Ah much better! Thank you!

2023-04-18 14:48 UTC, merged