Tech blog
torchbox/wagtail-torchbox pull request #480
Opened 2023-04-27 15:57 UTC by RealOrangeOne

WIP

As part of a Rock for _this_ quarter, we want to launch a tech blog. It'll be the same as the main blog, but with more tech-oriented blocks, and a simplified theme.

2023-06-26 12:31 UTC, zerolab requested changes
Did an initial, light pass with some local testing

2023-06-26 12:31 UTC, zerolab commented on tbx/project_styleguide/templates/patterns/pages/tech_blog/tech_blog_listing.html
> +        <div class="blog-listing__list" data-fetch-destination="blog-pages" data-fetch-max-pages="{{ blog_posts.paginator.num_pages }}">
can we use normal navigation? 
The load more thing is.. currently somewhat broken on the main blog and annoying trying to find historic posts

And it is utterly broken on the tech blog 🙈

2023-06-26 12:31 UTC, zerolab commented on tbx/project_styleguide/templates/patterns/pages/tech_blog/tech_blog_post.html
> +    {% for page_author in page.authors.all %}
showing the authors both at the top and bottom feels like overkill, especially if you have a shorter post and 2+ authors 😂 

<details>
<summary>example 📷 </summary>

![Screenshot 2023-06-26 at 13 14 06](https://github.com/torchbox/wagtail-torchbox/assets/31622/c088df78-18c2-48be-a590-81ae1051698e)

</details>

2023-06-26 12:31 UTC, zerolab commented on tbx/tech_blog/feeds.py
> +class TechBlogFeed(Feed):
it would be nice to have a feed description. currently that is `<description></description>`

2023-06-26 12:31 UTC, zerolab commented on tbx/tech_blog/migrations/0002_auto_20230626_1124.py
> +# Generated by Django 3.2.18 on 2023-06-26 10:24
nitpick: can we avoid auto-named migrations?
also, given this is a new feature, perhaps squash the migrations into a single initial one?

2023-06-26 12:31 UTC, zerolab commented on tbx/project_styleguide/templates/patterns/pages/blog/blog_detail.html
> +        {% include "patterns/molecules/author/author.html" with author=page_author.author item=page tag_link_base=blog_index_url tags=item.related_services.all %}
I find it weird how we add the tags on the author "card", but they relate to the blog post... but that is for another PR

2023-06-26 13:46 UTC, RealOrangeOne commented on tbx/tech_blog/migrations/0002_auto_20230626_1124.py
> +# Generated by Django 3.2.18 on 2023-06-26 10:24
All migrations will be squashed prior to merge, definitely. Single migration per app is the plan.

2023-06-26 13:53 UTC, zerolab commented on tbx/project_styleguide/templates/patterns/pages/tech_blog/tech_blog_post.html
> +    {% for page_author in page.authors.all %}
either the top or the bottom ones works for me, even if I'd lean heavier towards removing the top refs (this way you can have as many authors without it taking the whole page before reading content 😂 )

2023-06-26 13:59 UTC, RealOrangeOne commented on tbx/project_styleguide/templates/patterns/pages/tech_blog/tech_blog_listing.html
> +        <div class="blog-listing__list" data-fetch-destination="blog-pages" data-fetch-max-pages="{{ blog_posts.paginator.num_pages }}">
I've just fixed it for the tech blog (hadn't realised it was AJAX).

Conventional navigation would be nice, but there's no precedence for it in the site so far - it's all "Load more" etc.

2023-07-06 11:32 UTC, zerolab commented
This needs a rebase, but I'd say go for staging and let's get it out and iterate

2023-07-07 09:53 UTC, zerolab commented on tbx/core/migrations/0151_auto_20230707_1033.py
> +# Generated by Django 3.2.18 on 2023-07-07 09:33
<grumble>auto generated migrations names</grumble>

2023-07-07 09:56 UTC, zerolab commented on tbx/tech_blog/feeds.py
> +        return item.listing_summary
I dislike feed entries without a summary. given listing_summary can be empty we will end up more often than not with just the title in the feed :(

2023-07-07 10:03 UTC, RealOrangeOne commented on tbx/tech_blog/feeds.py
> +        return item.listing_summary
I completely agree. There's an item on the backlog to automatically derive `listing_summary` from the body content, which would solve that. I didn't want to add all these features into the MVP so we can get the MVP out faster (and help other people contribute).

2023-07-07 11:12 UTC, zerolab approved these changes
From now and henceforth, this MVP has my humble blessings

2023-12-19 09:55 UTC, helenb commented
Closing this for now as we are starting a new version of the torchbox.com site and don't currently have a separate tech blog specced for it.

2023-12-19 09:55 UTC, closed without merging