Fix: Added docs from Wagtail Kit
torchbox/wagtail-torchbox pull request #482
Opened 2023-05-04 14:43 UTC by victoriachan

Update documentation and README

2023-05-10 18:05 UTC, zerolab requested changes

2023-05-10 18:05 UTC, zerolab commented on docs/project_conventions.md
> +3. Make merge requests at https://github.com/torchbox/wagtail-torchbox/pulls
```suggestion
3. Make pull requests at https://github.com/torchbox/wagtail-torchbox/pulls
```

replace "merge request" with "pull request" everywhere since we are on GitHub

2023-06-21 10:22 UTC, helenb reviewed
Hi @engineervix I've left a few comments and queries. I haven't looked at the github pages changes or the changes to pyproject.toml as I'm not the best person to review those. I think for all the docs we should bear in mind that this is a public repo, so we need to be careful about any sensitive information. I am not sure how far documenting our intrastructure might be compromising - I wonder if someone in the security team should review this?

2023-06-21 10:22 UTC, helenb commented on README.md
> +This is done via [Heroku Github integration](https://devcenter.heroku.com/articles/github-integration).
Might be worth adding a comment here to say that you can view the progress of the deployment if you log into heroku

2023-06-21 10:22 UTC, helenb commented on docs/data_protection.md
> +This page gives an overview of potentially-sensitive data stored or processed by the Torchbox.com project.
should we include this info in a public github repo?

2023-06-21 10:22 UTC, helenb commented on docs/front-end/form-overrides.md
> +# Form overrides
Is tbx using crispy forms? I'm not sure this file is relevant

2023-06-21 10:22 UTC, helenb commented on docs/front-end/tooling.md
> +## React support
The React and Vue support info can be removed here

2023-06-21 10:22 UTC, helenb commented on docs/front-end/tooling.md
> +## Setting up a new project from the wagtail-kit tooling
this section can be removed

2023-06-21 10:22 UTC, helenb commented on docs/infrastructure.md
> +TODO:
Can this be updated?

2023-06-21 10:22 UTC, helenb commented on docs/support-runbook.md
> +!!! note
I think this note could be removed as for torchbox.com we are the client

2023-06-21 10:22 UTC, helenb commented on docs/upgrading.md
> +
Do we need to add anything here?

2023-06-21 11:11 UTC, RealOrangeOne commented on docs/deployment.md
> +| Staging     | `staging` | e.g. https://torchbox-staging.<staging domain> | e.g. `projectname-staging`    |
Issue: Placeholder values

2023-06-21 11:11 UTC, RealOrangeOne commented on docs/infrastructure.md
> +TODO:
Seconded. If we're going to have docs pages, they should at least be complete and correct.

2023-06-21 11:11 UTC, RealOrangeOne commented on docs/support-runbook.md
>  See also our [incident process](https://intranet.torchbox.com/propositions/design-and-build-proposition/delivering-projects/application-support/incident-process/) if you're not already following this
This links to the intranet, which should probably be removed.

2023-06-28 15:37 UTC, engineervix commented on README.md
> +This is done via [Heroku Github integration](https://devcenter.heroku.com/articles/github-integration).
Thanks, updated

2023-06-28 15:38 UTC, engineervix commented on docs/data_protection.md
> +This page gives an overview of potentially-sensitive data stored or processed by the Torchbox.com project.
I've removed it

2023-06-28 15:38 UTC, engineervix commented on docs/front-end/form-overrides.md
> +# Form overrides
Removed

2023-06-28 15:39 UTC, engineervix commented on docs/infrastructure.md
> +TODO:
Updated

2023-06-28 15:40 UTC, engineervix commented on docs/support-runbook.md
> +!!! note
Removed

2023-06-28 15:40 UTC, engineervix commented on docs/upgrading.md
> +
I've updated the section

2023-06-28 15:40 UTC, engineervix commented on docs/deployment.md
> +| Staging     | `staging` | e.g. https://torchbox-staging.<staging domain> | e.g. `projectname-staging`    |
Updated

2023-06-28 15:41 UTC, engineervix commented on docs/support-runbook.md
>  See also our [incident process](https://intranet.torchbox.com/propositions/design-and-build-proposition/delivering-projects/application-support/incident-process/) if you're not already following this
I've removed this file altogether, as i think this mostly applies to client projects

2023-06-29 18:19 UTC, helenb commented on docs/deployment.md
> +When you set up a server you should make sure the following scheduled tasks are set.
Is this vanilla documentation from kit? I wonder if we should change the wording here to reflect what actual tasks are running?

2023-06-29 18:19 UTC, helenb commented on docs/deployment.md
> +To deploy, merge your feature branch to `master` or `staging` branch. Once CI pipelines have passed, it will be deployed to the respective Heroku site automatically.
We should do this, but let's get these changes merged first and we could do that at the start of the next sprint.

2023-06-29 18:21 UTC, helenb commented on docs/index.md
> +This is the main website for torchbox.com, primarily built on the [Wagtail CMS](https://wagtail.org/).
Nitpick: no need for 'primarily'

2023-06-30 13:15 UTC, engineervix commented on docs/deployment.md
> +When you set up a server you should make sure the following scheduled tasks are set.
These are the only tasks available, so will maintain this for now.

2023-06-30 13:29 UTC, merged