New StreamField-powered SubPropositionPage based on SubServicePage
torchbox/wagtail-torchbox pull request #516
Opened 2023-07-31 16:36 UTC by engineervix

[Link to Ticket](https://torchbox.monday.com/boards/1192293412/pulses/1193045284)

### Description of Changes Made

This PR introduces a new page type -- `SubPropositionPage`, based on the existing `SubServicePage`, which has a fixed ordering of content on the rendered page. The  `SubPropositionPage` reorganizes the page content to use Streamfield blocks, thereby allowing content editors the freedom to arrange the content in any order.

> **Note**:
>
> The `SubServicePage` will be deprecated in a separete PR, alongside the `ServicePage` model, which is replaced by the `PropositionPage`.

### How to Test

TODO: add details when PR is complete

### Screenshots

<details>
<summary>Before (Wagtail Admin)</summary>
    
![admin](https://github.com/torchbox/wagtail-torchbox/assets/7713776/e3626f3f-1d5b-48c7-babb-e2e11287afcc)
    
</details>

<details>
<summary>Before (Template)</summary>

![frontend](https://github.com/torchbox/wagtail-torchbox/assets/7713776/a9cdf4e2-b829-4362-af24-dc7adb7aa9d2)
    
</details>

<details>
    <summary>After (Wagtail Admin)</summary>
    
</details>

<details>
    <summary>After (Template)</summary>
    
</details>

### MR Checklist

- [ ] Add a description of your pull request and instructions for the reviewer to verify your work.
- [ ] If your pull request is for a specific ticket, link to it in the description.
- [ ] Stay on point and keep it small so the merge request can be easily reviewed.
- [ ] Consider adding unit tests, especially for bug fixes. If you don't, tell us why.
- [ ] Tests and linting passes.
- [ ] Consider updating documentation. If you don't, tell us why.
- [ ] If relevant, list the environments / browsers in which you tested your changes.

2023-08-04 13:08 UTC, chris-lawton commented on tbx/propositions/blocks.py
> +        template="patterns/molecules/streamfield/blocks/key_points_summary.html",
I think this needs to use `patterns/molecules/streamfield/blocks/key-points.html` to match the styling of the key points used on the previous sub-service page. See example of key points here on Sub-service on the left and Sub-proposition on the right:

![Screenshot 2023-08-04 at 13 50 13](https://github.com/torchbox/wagtail-torchbox/assets/31627284/b02de132-21a1-4f90-976a-84d5ad1c9615)

2023-08-04 13:34 UTC, chris-lawton commented on tbx/propositions/blocks.py
> +        template="patterns/molecules/streamfield/blocks/client-logo-block.html",
This might be an existing issue on the live site but I spotted you can add a client logo with a link however the template assumes there will always be a link. Might just be a case of adding a conditional in `patterns/molecules/streamfield/blocks/client-logo-block.html`. 

![Screenshot 2023-08-04 at 14 32 26](https://github.com/torchbox/wagtail-torchbox/assets/31627284/08355d6b-c2a6-44f9-8a1d-e33976b78b1a)

2023-08-04 13:57 UTC, chris-lawton commented on tbx/propositions/blocks.py
> +        template="patterns/molecules/streamfield/blocks/client-logo-block.html",
Turns out it is an existing issue - https://github.com/torchbox/wagtail-torchbox/pull/522 : )

2023-08-07 15:16 UTC, victoriachan requested changes
Hi @engineervix ,

I love this! When I first saw the requirement, I couldn't imagine how best to organise the page blocks to accomodate the requirements. You've done this really nicely, and it is a very nice experience for the editor and looks good on the backend too.

I just have a few suggestions about refactoring. It isn't a big deal if you are short of time, as I know we are going to remake this site at some point.

One thing I noticed (to do with Wagtail, rather than your implementation) is that it is very hard to spot which block is triggering the validation error when saving a page with streamfields. However this issue is improved with wagtail 5, which this site will soon upgrade to. So no worries about that!

Another general suggestion is to add `is_creatable=False` to SubServicePage to prevent editors from using the page type until we fully remove it. I imagine there will be further ticket in future to remove it from the project.

2023-08-08 12:06 UTC, engineervix commented on tbx/project_styleguide/templates/patterns/molecules/in-page-nav/in-page-nav--sub-proposition.html
> +                    {{ title }}
I'm not sure about this one, the changes were made in #455.  It does look like this was probably for a11y reasons, as it's parent div has its `display` set to `none`:

https://github.com/torchbox/wagtail-torchbox/blob/9f8565a84883a85b0ccabb2fa3b7137532a266ad/tbx/static_src/sass/components/_in-page-nav.scss#L101

2023-08-08 12:13 UTC, engineervix commented on tbx/propositions/models.py
> +    )
I had struggled with implementation of this, as I was trying to avoid making too many changes to templates, which seemed to depend on `page.contact` or `page.contact_reasons`. However, I realize that the changes to be made are minor, so I have moved the fields to the `KeyPointsBlock` instead, since that's the only place where they are used.

The changes are in 7e41ad65.

2023-08-08 12:16 UTC, engineervix commented on tbx/project_styleguide/templates/patterns/molecules/hero/hero--sub-proposition.html
I like your suggestion, thank you!

I have made changes in 4d894df8

2023-08-08 12:17 UTC, engineervix commented
> Another general suggestion is to add `is_creatable=False` to SubServicePage to prevent editors from using the page type until we fully remove it. I imagine there will be further ticket in future to remove it from the project.

Thanks, I have added this in ec977229

2023-08-08 12:19 UTC, engineervix commented on tbx/propositions/models.py
> +        block_types = [
Awesome! I've made this DRYer in add6b4ffe8c29f41e2ae103b16b26671b622dc46

2023-08-08 12:28 UTC, engineervix commented on tbx/propositions/blocks.py
> +        template="patterns/molecules/streamfield/blocks/key_points_summary.html",
Hi @chris-lawton I have looked at this again, in the screenshot above, I think you added the _key points summary_ (part of the **Content Block** group) instead of _key points_ (in the **Page section** group). The latter uses the template `patterns/molecules/streamfield/blocks/key-points.html`:

https://github.com/torchbox/wagtail-torchbox/blob/add6b4ffe8c29f41e2ae103b16b26671b622dc46/tbx/propositions/blocks.py#L21-L45

2023-08-08 13:04 UTC, victoriachan commented on tbx/project_styleguide/templates/patterns/molecules/in-page-nav/in-page-nav--sub-proposition.html
> +                    {{ title }}
Ah. Fair enough. Thanks for checking!

2023-08-18 08:30 UTC, helenb commented on tbx/project_styleguide/templates/patterns/molecules/in-page-nav/in-page-nav--service.html
> +                <svg viewBox="0 0 130.37 156.35" aria-hidden="true" fill="var(--color--header-icon-color, #fd5765)" class="in-page-nav__logo"><path d="M129.64 82.82c-.2-1.59-2.3-1.96-3.08-.57-4.72 8.
This svg will need to be updated in line with the HCM changes that were separately applied to `in-page-nav--proposition.html` on the hcm integration branch.

2023-08-25 10:48 UTC, engineervix commented on tbx/project_styleguide/templates/patterns/molecules/in-page-nav/in-page-nav--service.html
> +                <svg viewBox="0 0 130.37 156.35" aria-hidden="true" fill="var(--color--header-icon-color, #fd5765)" class="in-page-nav__logo"><path d="M129.64 82.82c-.2-1.59-2.3-1.96-3.08-.57-4.72 8.
Thanks @helenb, done in 65a91a92

2023-08-25 10:56 UTC, engineervix commented
### Update (2023-Aug-25-Fri)

I have rebased this branch onto `main`, and made a few changes

- SubPropositionPageStoryBlock cleanup (6518fb44, [Monday ticket](https://torchbox.monday.com/boards/1192293412/pulses/1252433819), [another Monday ticket](https://torchbox.monday.com/boards/1192293412/pulses/1254121291))
- Template update based on @helenb's comment [here](https://github.com/torchbox/wagtail-torchbox/pull/516#discussion_r1298170931) (65a91a92)
- Merge migrations (8e81538e), since this was deployed to staging a while back

I have merged the above changes into `staging` for testing.

> **Note**
>
> The client logo block style is broken on SubPropositionPages. Needs fixing.

2023-10-16 09:58 UTC, engineervix commented
Hi @helenb I've rebased this branch against `main` and force-pushed.

2023-11-01 07:41 UTC, merged