Data migration sub proposition page
torchbox/wagtail-torchbox pull request #536
Opened 2023-08-25 05:55 UTC by engineervix

[Link to Ticket]()

### Description of Changes Made

### How to Test

### Screenshots

<details>
  <summary>Expand to see more</summary>

</details>

### MR Checklist

- [ ] Add a description of your pull request and instructions for the reviewer to verify your work.
- [ ] If your pull request is for a specific ticket, link to it in the description.
- [ ] Stay on point and keep it small so the merge request can be easily reviewed.
- [ ] Consider adding unit tests, especially for bug fixes. If you don't, tell us why.
- [ ] Tests and linting passes.
- [ ] Consider updating documentation. If you don't, tell us why.
- [ ] If relevant, list the environments / browsers in which you tested your changes.

2023-10-12 10:04 UTC, victoriachan requested changes
Hi Victor,

Wow, what a lot of code here. Well done for tackling it.

When testing locally with staging data, I encountered an error to do with the old testimonial streamfield (`AttributeError: 'StructValue' object has no attribute 'quote'`). I think we need to be more pessimistic about the existing streamfield data. We may need more exception handling added.

When the error was encountered, the command just failed halfway. I reverted it, but the revert didn't work fully as the page with the error was never added to the migration table. 

Hope it won't be too much work to make these changes, but as this concerns database changes, we need to be more cautious.

2023-10-13 12:45 UTC, engineervix commented on tbx/propositions/constants.py
> +TITLE_SUFFIX = "(NO LONGER IN USE)"
Thanks, updated in 5db0bfba

2023-10-13 12:47 UTC, engineervix commented on tbx/propositions/management/commands/migrate_subservicepages.py
> +                            "link": testimonial.link if testimonial.link else None,
Nice catch! I thought I was using latest staging data but I actually wasn't so I didn't encounter this when testing. After pulling in latest data I encountered the same error, and have fixed it in `9bcb2cbd`

2023-10-13 13:25 UTC, engineervix commented on tbx/propositions/management/commands/migrate_subservicepages.py
> +    pages = Page.objects.not_type(SubServicePage).specific()
Since `update_page_links()` is executed after the SubPropositionPage has already been created from a SubServicePage, the new SubPropositionPage will be updated if it contains a link to another SubServicePage

2023-10-13 18:04 UTC, engineervix commented on tbx/propositions/management/commands/migrate_subservicepages.py
> +            show_in_menus = old_page.show_in_menus
Thanks, updated in b90a0852.

2023-10-13 18:05 UTC, engineervix commented on tbx/propositions/management/commands/migrate_subservicepages.py
> +            copy_existing_blocks(old_page, new_page)
Thanks, updated in b016eb68, fd6c401f & e7210058

2023-10-13 18:06 UTC, engineervix commented on tbx/propositions/management/commands/migrate_subservicepages.py
> +            MigrationRecord.objects.create(
Good point, updated as part of previous comment, and also in 75ff893c

2023-10-14 00:10 UTC, engineervix commented on tbx/propositions/management/commands/undo_subservicepage_migration.py
> +        pages_to_manually_check = update_page_links()
Thanks! Gotta keep things DRY! Updated in ee4b1bb2 and febcc2b0

2023-10-14 00:17 UTC, engineervix commented
> Hi Victor,
> 
> Wow, what a lot of code here. Well done for tackling it.
> 
> When testing locally with staging data, I encountered an error to do with the old testimonial streamfield (`AttributeError: 'StructValue' object has no attribute 'quote'`). I think we need to be more pessimistic about the existing streamfield data. We may need more exception handling added.
> 
> When the error was encountered, the command just failed halfway. I reverted it, but the revert didn't work fully as the page with the error was never added to the migration table.
> 
> Hope it won't be too much work to make these changes, but as this concerns database changes, we need to be more cautious.

Thanks @victoriachan for taking the time to look into this, and thanks for the feedback. I've made some changes and tested again. If you're happy with the changes, I can backup staging DB then run this on staging for QA and verification.

I don't have access to the production DB, it would be great to pull the production DB and run the script against it so we see how it turns out.

2023-10-16 09:16 UTC, victoriachan commented on tbx/propositions/management/commands/migrate_subservicepages.py
> +    pages = Page.objects.not_type(SubServicePage).specific()
Ah yes, makes sense. Thanks for clarifying!

2023-10-16 09:18 UTC, victoriachan commented on tbx/propositions/management/commands/migrate_subservicepages.py
> +def update_page_links():
Yes, that's fair enough. That feature is rather new and has not been explored much yet. The documentation is not much either. Thanks for explaining!

2023-10-16 13:47 UTC, victoriachan requested changes
Hi Victor,

Thanks for making the changes. I've got just one more request to improve the way the new pk is derived, so instead of matching by title and slug, we try to match from the migration record. Unless you know of a good reason why that won't work.

Also I tested locally with the prod data, it is hard to tell if it worked as it is hard to check all the references, and won't be immediately obvious if something is missed. I'm wondering if we need tests after all. 

The undo had some errors, one to do with segmentation fault, and another to do with 'DeferringRelatedManager'. There are 31 of these errors. When checking the pages manually, I can see the original reverted SubServicePage pages no longer have their previous references, even after I ran `rebuild_references_index`. 

See the truncated report below for example of errors:

```
29 migration records have been deleted successfully.
29 SubPropositionPages have been deleted successfully.
29 SubServicePages have been successfully reverted to their previous state
The following pages require manual checking of links to avoid 404s:
1.  An Extra 3 Million Organic Clicks a Month for the NHS Website
------------------------------------------------------------
    Page id: 1319
    Streamfield name: Unknown
    Error: Page excluded from migration due to segmentation fault

...

3.  Innovation 
------------------------------------------------------------
    Page id: 1881
    Streamfield name: featured_blog_posts
    Error: 'DeferringRelatedManager' object has no attribute 'get_prep_value'
```

2023-10-16 13:47 UTC, victoriachan commented on tbx/propositions/management/commands/migrate_subservicepages.py
> +def update_rich_text_links(source, target, reverse=False):
See `update_stream_data`, the same applies here.

2023-10-16 13:47 UTC, victoriachan commented on tbx/propositions/management/commands/migrate_subservicepages.py
> +def replace_link(match, ids, reverse=False):
Can we pass in source and target instead of using reverse, to be consistent with the other functions? Also then we can use the `target` variable for `target_page_instance = get_migration_page(related_page_id=page_id, page_model=target)` as suggested by my comment below.

2023-11-01 08:08 UTC, merged