Support/wagtail 52
torchbox/wagtail-torchbox pull request #558
Opened 2023-11-29 11:56 UTC by lparsons396

**This PR upgrades Wagtail to version 5.2**

See [Monday ticket](https://torchbox.monday.com/boards/1318157635/pulses/1319732635) & [Wagtail 5.2 release notes](https://docs.wagtail.org/en/latest/releases/5.2.html#).

This branch builds on the Wagtail 5.1 upgrade https://github.com/torchbox/wagtail-torchbox/pull/544

The upgrade considerations actualise many of the deprecation warnings is the 5.1 upgrade and so few changes have been necessary here. Upgrading Wagtail has also necessitated the upgrading of django-filter (22.1 -> 23.4) and django-modelcluster (6.0 -> 6.1). All packages have been checked against the [package board](https://torchbox.monday.com/boards/1124794299) and use the appropriate tag / branch as needed.

2023-12-01 16:59 UTC, nickmoreton approved these changes
Hi @lparsons396  Thank for doing this. There's a few dependencies that could do with been bumped to latest releases before is merged.

2023-12-01 16:59 UTC, nickmoreton commented on pyproject.toml
>  Django = "~3.2.20"
Can you update this to the latest Django version please. ~3.2.23

2023-12-01 16:59 UTC, nickmoreton commented on pyproject.toml
>  django-pattern-library = "^1.0.0"
Can you run `poetry update django-pattern-library` to bump this to 1.1.0

2023-12-01 16:59 UTC, nickmoreton commented on pyproject.toml
>  django-pattern-library = "^1.0.0"
Also run the same command for:

- wagtail-webstories
- wagtailmedia

2023-12-07 18:38 UTC, zerolab commented on pyproject.toml
>  Django = "~3.2.20"
`~4.2.8`, pretty please!
and if you install `django-upgrade` locally, you can run `git ls-files --others --cached --exclude-standard -- '*.py' | xargs django-upgrade --target 4.2` ;)

2023-12-08 18:13 UTC, zerolab commented on pyproject.toml
>  python = "^3.9"
this would be the perfect time to make the jump to 3.11 (the Dockerfile will need updating too)

2023-12-12 11:42 UTC, zerolab requested changes

2023-12-13 09:10 UTC, lparsons396 commented
Thanks for your review @zerolab , let me know if there's anything else! :)

2023-12-13 09:15 UTC, zerolab approved these changes
:shipit:

2023-12-19 12:36 UTC, zerolab commented
@helenb imho this is ready to go too

2023-12-19 12:41 UTC, helenb commented
> @helenb imho this is ready to go too

From @katdom13 on slack:

"I’m also encountering this error during staging deployment for 5.2:
TypeError: cache_control didn't receive an HttpRequest. If you are decorating a classmethod, be sure to use @method_decorator.
I can replicate this. I reverted the change on staging for now and will investigate this along with the above tomorrow."

I will also need to wait to hear if 5.2 has been tested on staging.

2023-12-19 12:58 UTC, zerolab commented
@helenb @katdom13 that would be https://github.com/wagtail/wagtail.org/pull/443/commits/3410fbca4f32cb3556bb40aff4aca07c06da29b5

2023-12-20 02:47 UTC, katdom13 commented on tbx/urls.py
> +)
This fixes the error on app startup
```
cache_control didn't receive an HttpRequest. If you are decorating a classmethod, be sure to use @method_decorator.
```

![image](https://github.com/torchbox/wagtail-torchbox/assets/26372762/510bab4b-3faa-4ea6-886e-f72a1420c38a)

2023-12-20 03:14 UTC, katdom13 commented
> > @helenb imho this is ready to go too
> 
> From @katdom13 on slack:
> 
> "I’m also encountering this error during staging deployment for 5.2: TypeError: cache_control didn't receive an HttpRequest. If you are decorating a classmethod, be sure to use @method_decorator. I can replicate this. I reverted the change on staging for now and will investigate this along with the above tomorrow."
> 
> I will also need to wait to hear if 5.2 has been tested on staging.

Hi @helenb ,
Apologies, I reverted this yesterday on staging when I saw the errors, but failed to remove the tag here in this MR. Staging should still be in 5.1

2023-12-20 04:04 UTC, katdom13 commented
Hi @zerolab ,


> > `TypeError: cache_control didn't receive an HttpRequest. If you are decorating a classmethod, be sure to use @method_decorator.`
> > @helenb @katdom13 the fix for that would be [wagtail/wagtail.org@3410fbc](https://github.com/wagtail/wagtail.org/commit/3410fbca4f32cb3556bb40aff4aca07c06da29b5)

I saw this just now and updated the fix accordingly. Could you please review the changes starting at:
https://github.com/torchbox/wagtail-torchbox/pull/558/commits/bf060556c1a0267ff00bf1c896f86900eac548d5

Thanks!

2023-12-20 09:26 UTC, zerolab commented
@katdom13 they LGTM. Added another fix (e7d3bb5)

2023-12-20 10:40 UTC, helenb commented
@katdom13 I've created this ticket for Anna to test this on staging so we can be clear when this is ready to be merged: https://torchbox.monday.com/boards/1192293412/pulses/1347671612

2023-12-21 08:09 UTC, merged